import type { FeedDefinition } from "./types";

export const feeds: FeedDefinition[] = [
  // Major Financial News Outlets
  {
    id: "reuters-news-releases",
    name: "Thomson Reuters News Releases",
    url: "https://ir.thomsonreuters.com/rss/news-releases.xml?items=15",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["US", "EU", "ASIA"],
  },
  {
    id: "bloomberg",
    name: "Bloomberg Markets",
    url: "https://feeds.bloomberg.com/markets/news.rss",
    leaning: "center",
    industries: ["finance", "markets", "tech"],
    regions: ["US", "EU", "ASIA"],
  },
  {
    id: "financial-times",
    name: "Financial Times",
    url: "https://www.ft.com/?format=rss",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["US", "EU", "UK"],
  },
  {
    id: "wsj-markets",
    name: "Wall Street Journal Markets",
    url: "https://feeds.content.dowjones.io/public/rss/RSSMarketsMain",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["US"],
  },
  {
    id: "wsj-world",
    name: "Wall Street Journal World",
    url: "https://feeds.content.dowjones.io/public/rss/RSSWorldNews",
    leaning: "center",
    industries: ["finance", "markets", "world"],
    regions: ["US"],
  },
  {
    id: "wsj-business",
    name: "Wall Street Journal Business",
    url: "https://feeds.content.dowjones.io/public/rss/socialeconomyfeed",
    leaning: "center",
    industries: ["finance", "markets", "business"],
    regions: ["US"],
  },
  {
    id: "cnbc-top",
    name: "CNBC Top News",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114",
    leaning: "left",
    industries: ["finance", "tech", "markets"],
    regions: ["US"],
  },
  {
    id: "cnbc-markets",
    name: "CNBC Markets",
    url: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    leaning: "left",
    industries: ["finance", "markets"],
    regions: ["US"],
  },
  {
    id: "cnbc-investing",
    name: "CNBC Investing",
    url: "https://www.cnbc.com/id/15839135/device/rss/rss.html",
    leaning: "left",
    industries: ["finance", "markets", "investing"],
    regions: ["US"],
  },
  {
    id: "marketwatch-top",
    name: "MarketWatch Top Stories",
    url: "https://feeds.content.dowjones.io/public/rss/mw_topstories",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["US"],
  },
  {
    id: "marketwatch-breaking",
    name: "MarketWatch Breaking News",
    url: "https://feeds.content.dowjones.io/public/rss/mw_bulletins",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["US"],
  },

  // Australian & New Zealand Sources
  {
    id: "news-au-finance",
    name: "News.com.au Finance",
    url: "https://www.news.com.au/content-feeds/latest-news-finance/",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["AU"],
  },
  {
    id: "news-au-world",
    name: "News.com.au World",
    url: "https://www.news.com.au/content-feeds/latest-news-world/",
    leaning: "center",
    industries: ["finance", "markets", "world"],
    regions: ["AU", "WORLD"],
  },
  {
    id: "nz-herald-business",
    name: "NZ Herald Business",
    url: "https://www.nzherald.co.nz/arc/outboundfeeds/rss/section/business/?outputType=xml&_website=nzh",
    leaning: "center",
    industries: ["finance", "markets", "business"],
    regions: ["NZ"],
  },

  // Technology & Finance
  {
    id: "techcrunch",
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    leaning: "center",
    industries: ["tech"],
    regions: ["US"],
  },
  {
    id: "news-au-tech",
    name: "News.com.au Technology",
    url: "https://www.news.com.au/content-feeds/latest-news-technology/",
    leaning: "center",
    industries: ["tech"],
    regions: ["AU"],
  },

  // Additional Financial Sources
  {
    id: "investing-com",
    name: "Investing.com Top News",
    url: "https://www.investing.com/rss/news.rss",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["US", "EU", "ASIA"],
  },

  // Major News Outlets
  {
    id: "nytimes-homepage",
    name: "New York Times Top Stories",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    leaning: "left",
    industries: ["finance", "markets", "tech", "politics", "world"],
    regions: ["US", "WORLD"],
  },
  {
    id: "foxnews-latest",
    name: "Fox News Latest",
    url: "http://feeds.foxnews.com/foxnews/latest",
    leaning: "right",
    industries: ["finance", "markets", "tech", "politics", "world"],
    regions: ["US", "WORLD"],
  },
  {
    id: "washingtonpost-world",
    name: "Washington Post World",
    url: "https://feeds.washingtonpost.com/rss/world",
    leaning: "left",
    industries: ["politics", "world"],
    regions: ["US", "WORLD"],
  },
  {
    id: "washingtonpost-business",
    name: "Washington Post Business",
    url: "https://feeds.washingtonpost.com/rss/business",
    leaning: "left",
    industries: ["finance", "markets", "business"],
    regions: ["US"],
  },
  {
    id: "washingtonpost-technology",
    name: "Washington Post Technology",
    url: "https://feeds.washingtonpost.com/rss/business/technology",
    leaning: "left",
    industries: ["tech"],
    regions: ["US"],
  },
  {
    id: "rt",
    name: "RT",
    url: "https://www.rt.com/rss/",
    leaning: "center",
    industries: ["politics", "world"],
    regions: ["WORLD"],
  },
  {
    id: "nypost",
    name: "New York Post",
    url: "https://nypost.com/feed/",
    leaning: "right",
    industries: ["finance", "markets", "tech", "politics", "world"],
    regions: ["US", "WORLD"],
  },
  {
    id: "economist",
    name: "The Economist",
    url: "https://www.economist.com/rss",
    leaning: "center",
    industries: ["finance", "markets", "tech", "politics", "world"],
    regions: ["US", "EU", "UK", "WORLD"],
  },
];
