import type { FeedDefinition } from "./types";

export const feeds: FeedDefinition[] = [
  // Major Financial News Outlets
  {
    id: "reuters-finance",
    name: "Reuters Finance",
    url: "https://www.reutersagency.com/feed/?taxonomy=best-topics&post_type=best",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["US", "EU", "ASIA"],
  },
  {
    id: "reuters-news-releases",
    name: "Thomson Reuters News Releases",
    url: "https://ir.thomsonreuters.com/rss/news-releases.xml?items=15",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["US", "EU", "ASIA"],
  },
  {
    id: "bloomberg",
    name: "Bloomberg Markets",
    url: "https://feeds.bloomberg.com/markets/news.rss",
    leaning: "center",
    industries: ["finance", "markets", "tech"],
    regions: ["US", "EU", "ASIA"],
  },
  {
    id: "financial-times",
    name: "Financial Times",
    url: "https://www.ft.com/?format=rss",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["US", "EU", "UK"],
  },
  {
    id: "wsj-markets",
    name: "Wall Street Journal Markets",
    url: "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["US"],
  },
  {
    id: "wsj-business",
    name: "Wall Street Journal Business",
    url: "https://feeds.a.dj.com/rss/RSSBusinessNews.xml",
    leaning: "center",
    industries: ["finance", "markets", "business"],
    regions: ["US"],
  },
  {
    id: "cnbc-top",
    name: "CNBC Top News",
    url: "https://feeds.nbcnews.com/nbcnews/public/topstories",
    leaning: "left",
    industries: ["finance", "tech", "markets"],
    regions: ["US"],
  },
  {
    id: "cnbc-markets",
    name: "CNBC Markets",
    url: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    leaning: "left",
    industries: ["finance", "markets"],
    regions: ["US"],
  },
  {
    id: "cnbc-investing",
    name: "CNBC Investing",
    url: "https://www.cnbc.com/id/15839135/device/rss/rss.html",
    leaning: "left",
    industries: ["finance", "markets", "investing"],
    regions: ["US"],
  },
  {
    id: "marketwatch-top",
    name: "MarketWatch Top Stories",
    url: "https://www.marketwatch.com/rss/topstories",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["US"],
  },
  {
    id: "marketwatch-breaking",
    name: "MarketWatch Breaking News",
    url: "https://www.marketwatch.com/rss/breaking-news",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["US"],
  },

  // Australian & New Zealand Sources
  {
    id: "news-au-finance",
    name: "News.com.au Finance",
    url: "https://www.news.com.au/content-feeds/latest-news-finance/",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["AU"],
  },
  {
    id: "news-au-world",
    name: "News.com.au World",
    url: "https://www.news.com.au/content-feeds/latest-news-world/",
    leaning: "center",
    industries: ["finance", "markets", "world"],
    regions: ["AU", "WORLD"],
  },
  {
    id: "nz-herald-business",
    name: "NZ Herald Business",
    url: "https://www.nzherald.co.nz/arc/outboundfeeds/rss/section/business/?outputType=xml&_website=nzh",
    leaning: "center",
    industries: ["finance", "markets", "business"],
    regions: ["NZ"],
  },

  // Technology & Finance
  {
    id: "techcrunch",
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    leaning: "center",
    industries: ["tech"],
    regions: ["US"],
  },
  {
    id: "news-au-tech",
    name: "News.com.au Technology",
    url: "https://www.news.com.au/content-feeds/latest-news-technology/",
    leaning: "center",
    industries: ["tech"],
    regions: ["AU"],
  },
  {
    id: "reuters-tech",
    name: "Reuters Technology",
    url: "https://www.reutersagency.com/feed/?taxonomy=best-topics&post_type=best&best-topics=technology",
    leaning: "center",
    industries: ["tech"],
    regions: ["US", "EU", "ASIA"],
  },

  // Additional Financial Sources
  {
    id: "yahoo-finance",
    name: "Yahoo Finance",
    url: "https://feeds.finance.yahoo.com/rss/2.0/headline",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["US"],
  },
  {
    id: "investing-com",
    name: "Investing.com Top News",
    url: "https://www.investing.com/rss/news.rss",
    leaning: "center",
    industries: ["finance", "markets"],
    regions: ["US", "EU", "ASIA"],
  },
];
